server:
  port: 8888
spring:
  application:
    name: config-server-remote
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brucelee186/spring_cloud.git
          search-paths: config
          username: brucelee186
          passphrase: 71415937Ab
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/